version: '2'

services:  
  laravel:    
    build: .    
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.36    
    volumes:
       - db_data:/var/lib/mysql    
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app
volumes:
    db_data: