version: '2'

services:  
  rb-laravel:    
    build: .    
    ports:
      - "5000:80"    
    depends_on:
      - rb-mysql
  rb-mysql:    
    image: mysql:5.6.36    
    volumes:
       - db_data:/var/lib/mysql    
    environment:
      - MYSQL_ROOT_PASSWORD=password123456
      - MYSQL_DATABASE=roombooking
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
    db_data: